### ISSUE TITLE
Kod dotyczący implementacji z izolacją jest niewidoczny

### ISSUE THREAD

**Issue by pago21** [jaktestowac/playwright-info-blog#2]
Dotyczy to artykułu https://playwright.info/nowa-zakladka-w-playwright.

Ogólnie kod jest ale trzeba się do niego dostać mocno naokoło :)

Na Chromie w rozdzielczości 1920x1080 tak to się prezentuje:
![image](https://github.com/jaktestowac/playwright-info-blog/assets/121342437/ae1d4283-c824-4832-bb2a-a174f7fe0c19)

**Comment by jaktestowac** [comment]
Błąd znaleziony i naprawiony - powinno już działać :)
